# generated by datamodel-codegen:
#   filename:  idta_asset_interfaces_mapping_submodel_template_schema.json
#   timestamp: 2024-09-27T11:52:58+00:00

from __future__ import annotations

from typing import List, Union
from uuid import UUID

from pydantic import BaseModel, Field


class MappingConfigurations(BaseModel):
    id_short: str = Field(..., examples=['MappingConfigurations'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/AssetInterfacesMappingConfiguration/1/0/MappingConfiguration'
        ],
        title='Semantic Id',
    )
    InterfaceReference: Union[str, int, UUID] = Field(
        ..., examples=[], title='Interfacereference'
    )
    MappingSourceSinkRelations: List[List] = Field(
        ..., examples=[], title='Mappingsourcesinkrelations'
    )


class AssetInterfacesMappingConfiguration(BaseModel):
    id_short: str = Field(
        ..., examples=['AssetInterfacesMappingConfiguration'], title='Id Short'
    )
    description: str = Field(..., examples=[''], title='Description')
    id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/SubmodelTemplate/AssetInterfacesMappingConfiguration/1/0/'
        ],
        title='Id',
    )
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/AssetInterfacesMappingConfiguration/1/0/Submodel'
        ],
        title='Semantic Id',
    )
    MappingConfigurations: List[MappingConfigurations] = Field(
        ..., examples=[], title='Mappingconfigurations'
    )
