site_name: aas-middleware Documentation
theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search
  - include_dir_to_nav
  - mkdocstrings:
      default_handler: python
      # handlers:
      #   python:
      #     paths: [aas_middleware]


nav:
- Home: index.md
- Topical Guides: Guides
- Api Reference: API_reference

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences