# generated by datamodel-codegen:
#   filename:  ProvisionofSimulationModelsAAS_schema.json
#   timestamp: 2024-09-28T13:27:30+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class BinaryConnector(BaseModel):
    id_short: str = Field(..., examples=['BinaryConnector'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/BinaryConnector/1/0'],
        title='Semantic Id',
    )
    binary_con_name: str = Field(..., examples=[], title='Binary Con Name')
    binary_con_description: str = Field(
        ..., examples=[], title='Binary Con Description'
    )


class Email(BaseModel):
    id_short: str = Field(..., examples=['Email'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ..., examples=['0173-1#02-AAQ836#005'], title='Semantic Id'
    )
    type_of_email_address: str = Field(..., examples=[], title='Type Of Email Address')
    email_address: str = Field(..., examples=[], title='Email Address')
    type_of_public_key: str = Field(..., examples=[], title='Type Of Public Key')
    public_key: str = Field(..., examples=[], title='Public Key')


class ModelFileVersion(BaseModel):
    id_short: str = Field(..., examples=['ModelFileVersion'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/ModelFileVersion/1/0'],
        title='Semantic Id',
    )
    model_version_id: str = Field(..., examples=[], title='Model Version Id')
    model_file_release_notes_txt: str = Field(
        ..., examples=[], title='Model File Release Notes Txt'
    )


class Phone(BaseModel):
    id_short: str = Field(..., examples=['Phone'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/zvei/nameplate/1/0/ContactInformations/ContactInformation/Phone'
        ],
        title='Semantic Id',
    )
    type_of_telephone: str = Field(..., examples=[], title='Type Of Telephone')
    telephone_number: str = Field(..., examples=[], title='Telephone Number')
    available_time: str = Field(..., examples=[], title='Available Time')


class SimModManufacturerInformation(BaseModel):
    id_short: str = Field(
        ..., examples=['SimModManufacturerInformation'], title='Id Short'
    )
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/SimulationModels/SimModManufacturerInformation/1/0'
        ],
        title='Semantic Id',
    )
    company: str = Field(..., examples=[], title='Company')
    language: str = Field(..., examples=[], title='Language')
    email: Email = Field(..., examples=[])
    phone: Phone = Field(..., examples=[])


class SimPurpose(BaseModel):
    id_short: str = Field(..., examples=['SimPurpose'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/SimPurpose/1/0'],
        title='Semantic Id',
    )
    pos_sim_purpose: str = Field(..., examples=[], title='Pos Sim Purpose')
    neg_sim_purpose: str = Field(..., examples=[], title='Neg Sim Purpose')


class TestedToolSolverAlgorithm(BaseModel):
    id_short: str = Field(..., examples=['TestedToolSolverAlgorithm'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/SimulationModels/TestedToolSolverAlgorithm/1/0'
        ],
        title='Semantic Id',
    )
    solver_algorithm: str = Field(..., examples=[], title='Solver Algorithm')
    tool_solver_further_description: str = Field(
        ..., examples=[], title='Tool Solver Further Description'
    )
    tolerance: float = Field(..., examples=[], title='Tolerance')


class Variable(BaseModel):
    id_short: str = Field(..., examples=['Variable'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/Variable/1/0'],
        title='Semantic Id',
    )
    variable_name: str = Field(..., examples=[], title='Variable Name')
    range: str = Field(..., examples=[], title='Range')
    variable_type: str = Field(..., examples=[], title='Variable Type')
    variable_description: str = Field(..., examples=[], title='Variable Description')
    unit_list: str = Field(..., examples=[], title='Unit List')
    unit_description: str = Field(..., examples=[], title='Unit Description')
    variable_causality: str = Field(..., examples=[], title='Variable Causality')
    variable_prefix: str = Field(..., examples=[], title='Variable Prefix')


class ModelFile(BaseModel):
    id_short: str = Field(..., examples=['ModelFile'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/ModelFile/1/0'],
        title='Semantic Id',
    )
    model_file_type: str = Field(..., examples=[], title='Model File Type')
    model_file_version: ModelFileVersion = Field(..., examples=[])


class PortsConnector(BaseModel):
    id_short: str = Field(..., examples=['PortsConnector'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/PortsConnector/1/0'],
        title='Semantic Id',
    )
    port_connector_name: str = Field(..., examples=[], title='Port Connector Name')
    port_con_description: str = Field(..., examples=[], title='Port Con Description')
    variable: Variable = Field(..., examples=[])


class SolverAndTolerances(BaseModel):
    id_short: str = Field(..., examples=['SolverAndTolerances'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=[
            'https://admin-shell.io/idta/SimulationModels/SolverAndTolerances/1/0'
        ],
        title='Semantic Id',
    )
    step_size_control_needed: bool = Field(
        ..., examples=[], title='Step Size Control Needed'
    )
    fixed_step_size: float = Field(..., examples=[], title='Fixed Step Size')
    stiff_solver_needed: bool = Field(..., examples=[], title='Stiff Solver Needed')
    solver_included: bool = Field(..., examples=[], title='Solver Included')
    tested_tool_solver_algorithm: TestedToolSolverAlgorithm = Field(..., examples=[])


class Ports(BaseModel):
    id_short: str = Field(..., examples=['Ports'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/Ports/1/0'],
        title='Semantic Id',
    )
    ports_connector: PortsConnector = Field(..., examples=[])
    binary_connector: BinaryConnector = Field(..., examples=[])


class SimulationTool(BaseModel):
    id_short: str = Field(..., examples=['SimulationTool'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/SimulationTool/1/0'],
        title='Semantic Id',
    )
    sim_tool_name: str = Field(..., examples=[], title='Sim Tool Name')
    dependency_sim_tool: str = Field(..., examples=[], title='Dependency Sim Tool')
    compiler: str = Field(..., examples=[], title='Compiler')
    solver_and_tolerances: SolverAndTolerances = Field(..., examples=[])


class Environment(BaseModel):
    id_short: str = Field(..., examples=['Environment'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/Environment/1/0'],
        title='Semantic Id',
    )
    operating_system: str = Field(..., examples=[], title='Operating System')
    tool_environment: str = Field(..., examples=[], title='Tool Environment')
    dependency_environment: str = Field(
        ..., examples=[], title='Dependency Environment'
    )
    visualization_information: str = Field(
        ..., examples=[], title='Visualization Information'
    )
    simulation_tool: SimulationTool = Field(..., examples=[])


class SimulationModel(BaseModel):
    id_short: str = Field(..., examples=['SimulationModel'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/SimulationModel/1/0'],
        title='Semantic Id',
    )
    summary: str = Field(..., examples=[], title='Summary')
    sim_purpose: SimPurpose = Field(..., examples=[])
    type_of_model: str = Field(..., examples=[], title='Type Of Model')
    scope_of_model: str = Field(..., examples=[], title='Scope Of Model')
    license_model: str = Field(..., examples=[], title='License Model')
    engineering_domain: str = Field(..., examples=[], title='Engineering Domain')
    environment: Environment = Field(..., examples=[])
    model_file: ModelFile = Field(..., examples=[])
    param_method: str = Field(..., examples=[], title='Param Method')
    init_state_method: str = Field(..., examples=[], title='Init State Method')
    default_sim_time: float = Field(..., examples=[], title='Default Sim Time')
    sim_mod_manufacturer_information: SimModManufacturerInformation = Field(
        ..., examples=[]
    )
    ports: Ports = Field(..., examples=[])


class SimulationModels(BaseModel):
    id_short: str = Field(..., examples=['SimulationModels'], title='Id Short')
    description: str = Field(..., examples=[''], title='Description')
    id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SubmodelTemplate/SimulationModels/1/0'],
        title='Id',
    )
    semantic_id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/SimulationModels/SimulationModels/1/0'],
        title='Semantic Id',
    )
    simulation_model: SimulationModel = Field(..., examples=[])


class ProvisionofSimulationModelsAAS(BaseModel):
    id_short: str = Field(
        ..., examples=['ProvisionofSimulationModelsAAS'], title='Id Short'
    )
    description: str = Field(..., examples=[''], title='Description')
    id: str = Field(
        ...,
        examples=['https://admin-shell.io/idta/aas/SimulationModels/1/0'],
        title='Id',
    )
    simulation_models: SimulationModels = Field(..., examples=[])
